name: KCCacheProxy Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    # npm install
    - run: apt install -y p7zip-full
    - run: mkdir -p out/KCCacheProxy/
    - run: npm install
    - run: npm install pkg -g
    - run: pkg --out-path out src/proxy/proxy.js
